//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>About HQ</summary>
	[PublishedContentModel("aboutHQ")]
	public partial class AboutHQ : PublishedContentModel, IHeadlineBodytext
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutHQ";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutHQ(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutHQ, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// about_fullWidthImage
		///</summary>
		[ImplementPropertyType("about_fullWidthImage")]
		public IPublishedContent About_fullWidthImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("about_fullWidthImage"); }
		}

		///<summary>
		/// contact info
		///</summary>
		[ImplementPropertyType("contactInfo")]
		public IHtmlString ContactInfo
		{
			get { return this.GetPropertyValue<IHtmlString>("contactInfo"); }
		}

		///<summary>
		/// Bodytext
		///</summary>
		[ImplementPropertyType("bodytext")]
		public IHtmlString Bodytext
		{
			get { return Umbraco.Web.PublishedContentModels.HeadlineBodytext.GetBodytext(this); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.HeadlineBodytext.GetHeadline(this); }
		}
	}
}
