//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1083 with alias "award"
	/// <summary>Award</summary>
	public partial interface IAward : IPublishedContent
	{
		/// <summary>Description</summary>
		string Description { get; }

		/// <summary>headlineAward</summary>
		string HeadlineAward { get; }
	}

	/// <summary>Award</summary>
	[PublishedContentModel("award")]
	public partial class Award : PublishedContentModel, IAward
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "award";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Award(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Award, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return GetDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetDescription(IAward that) { return that.GetPropertyValue<string>("description"); }

		///<summary>
		/// headlineAward
		///</summary>
		[ImplementPropertyType("headlineAward")]
		public string HeadlineAward
		{
			get { return GetHeadlineAward(this); }
		}

		/// <summary>Static getter for headlineAward</summary>
		public static string GetHeadlineAward(IAward that) { return that.GetPropertyValue<string>("headlineAward"); }
	}
}
