//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Room Box</summary>
	[PublishedContentModel("roomBox")]
	public partial class RoomBox : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "roomBox";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public RoomBox(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<RoomBox, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Event Github Link
		///</summary>
		[ImplementPropertyType("eventGithubLink")]
		public string EventGithubLink
		{
			get { return this.GetPropertyValue<string>("eventGithubLink"); }
		}

		///<summary>
		/// Event Host: Input The host name(s) for the event
		///</summary>
		[ImplementPropertyType("eventHost")]
		public string EventHost
		{
			get { return this.GetPropertyValue<string>("eventHost"); }
		}

		///<summary>
		/// Event Title: Input title of the event
		///</summary>
		[ImplementPropertyType("eventTitle")]
		public string EventTitle
		{
			get { return this.GetPropertyValue<string>("eventTitle"); }
		}

		///<summary>
		/// Event Video Link
		///</summary>
		[ImplementPropertyType("eventVideoLink")]
		public string EventVideoLink
		{
			get { return this.GetPropertyValue<string>("eventVideoLink"); }
		}

		///<summary>
		/// Room Name: Choose the event room
		///</summary>
		[ImplementPropertyType("roomName")]
		public string RoomName
		{
			get { return this.GetPropertyValue<string>("roomName"); }
		}
	}
}
