//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Speaker</summary>
	[PublishedContentModel("speaker")]
	public partial class Speaker : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "speaker";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Speaker(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Speaker, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Speaker description
		///</summary>
		[ImplementPropertyType("speakerDescription")]
		public string SpeakerDescription
		{
			get { return this.GetPropertyValue<string>("speakerDescription"); }
		}

		///<summary>
		/// Speaker name
		///</summary>
		[ImplementPropertyType("speakerName")]
		public string SpeakerName
		{
			get { return this.GetPropertyValue<string>("speakerName"); }
		}

		///<summary>
		/// Speaker pic
		///</summary>
		[ImplementPropertyType("speakerPic")]
		public IPublishedContent SpeakerPic
		{
			get { return this.GetPropertyValue<IPublishedContent>("speakerPic"); }
		}
	}
}
