//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Vote</summary>
	[PublishedContentModel("vote")]
	public partial class Vote : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "vote";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Vote(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Vote, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// ProjectGuid
		///</summary>
		[ImplementPropertyType("projectGuid")]
		public string ProjectGuid
		{
			get { return this.GetPropertyValue<string>("projectGuid"); }
		}

		///<summary>
		/// ticketID
		///</summary>
		[ImplementPropertyType("ticketID")]
		public int TicketID
		{
			get { return this.GetPropertyValue<int>("ticketID"); }
		}

		///<summary>
		/// VoteTime
		///</summary>
		[ImplementPropertyType("voteTime")]
		public DateTime VoteTime
		{
			get { return this.GetPropertyValue<DateTime>("voteTime"); }
		}
	}
}
